[package]
name = "forky_play"
version = {workspace=true}
edition = {workspace=true}
license-file = {workspace=true}
readme = {workspace=true}
description = {workspace=true}
repository = {workspace=true}

[dependencies]
forky_core = {workspace = true }
bevy = {workspace = true}
bevy-inspector-egui = {workspace = true}

[dev-dependencies]
forky_test = {workspace = true }