[package]
name = "forky_play"
version = {workspace=true}
edition = {workspace=true}
license-file = {workspace=true}
readme = {workspace=true}
description = {workspace=true}
repository = {workspace=true}

[dependencies]
forky_core = {workspace = true }
bevy = {workspace = true}
bevy-inspector-egui = {workspace = true}
enigo = {path = "../../../../work-ref/enigo", version = "0.0.14"}

[dev-dependencies]
forky_test = {workspace = true }
inventory = {workspace = true}

[[test]]
name = "forky"
path = "test/main.rs"
harness = false
