[package]
name = "forky_cli"
version = {workspace=true}
edition = {workspace=true}
license-file = {workspace=true}
readme = {workspace=true}
description = {workspace=true}
repository = {workspace=true}

[dependencies]
forky_core = {path = "../forky_core"}
notify = {workspace = true}
# notify-debouncer-mini = {workspace = true}
