# https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
resolver = "2" # Important! wgpu/Bevy needs this!
members = [
	# "crates/*"
	"crates/forky",
	"crates/forky_ai",
	"crates/forky_cli",
	"crates/forky_core",
	"crates/forky_test",
	"crates/forky_esp",
	"crates/forky_play",
	"crates/forky_web",
	"crates/sweet",
	"crates/sweet/macros",
]
exclude = ["crates/bevy_webxr"]

[workspace.package]
version = "0.1.31"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
authors = ["Peter Hayman <peteyhayman@gmail.com>"]
description = "Rust Utilities"
documentation = "https://github.com/mrchantey/forky"
repository = "https://github.com/mrchantey/forky"

[workspace.dependencies]
### internal ###
forky = { path = "./crates/forky", version = "0.*" }
forky_ai = { path = "./crates/forky_ai", version = "0.*" }
forky_cli = { path = "./crates/forky_cli", version = "0.*" }
forky_core = { path = "./crates/forky_core", version = "0.*" }
forky_fs = { path = "./crates/forky_fs", version = "0.*" }
forky_esp = { path = "./crates/forky_esp", version = "0.*" }
forky_play = { path = "./crates/forky_play", version = "0.*" }
forky_web = { path = "./crates/forky_web", version = "0.*" }
sweet = { path = "./crates/sweet", version = "0.*" }
sweet_macros = { path = "./crates/sweet/macros", version = "0.*" }

### game ###
bevy = { version = "0.11.0" }
bevy-inspector-egui = "0.19.0"
bevy_mod_debugdump = "0.8.0"
bevy_rapier3d = { version = "0.22.0", features = ["debug-render-3d"] }
bevy_easings = "0.11.1"
wgpu = { version = "0.16.0" }

### AI ###
chatgpt_rs = { version = "1.1.1", features = ["streams"] }

### utility ###
anyhow = "1"
time = "0.3.20"
petgraph = "0.6.3"
bytemuck = "1.13.1"

## Attributes ###
num-traits = "0.2.15"
derive_deref = "1.1.1"
strum = "0.24.1"
strum_macros = "0.24.1"
extend = "1.1.2"

### IO ###
clap = { version = "4.2.2", features = ["derive"] }
colorize = "0.1.0"
crossterm = "0.25.0"
dotenv = "0.15.0"
gag = "1.0.0"
glob = "0.3.1"
notify = "6.0.1"
notify-debouncer-full = "0.2.0"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
postcard = { version = "1.0.4", features = ["alloc"] }

### Math ###
sha2 = "0.10.7"
hex = "0.4.3"
rand = { version = "0.8.5" }
getrandom = { version = "0.2.9", features = ["js"] }
rgb = "0.8.34"
plotters = "0.3.4"
plotters-canvas = "0.3.0"

### Async ###
futures = "0.3.28"
futures-util = "0.3.28"
tokio = { version = "1.27.0", features = [
	"macros",
	"rt",
	"rt-multi-thread",
	"time",
] }
tokio-stream = "0.1.14"
rayon = "1.7.0"

### macros ###
inventory = "0.3.2"
backtrace = "0.3.66"
proc-macro2 = "1.0.47"
syn = { version = "1.0.103", features = ["full"] }
quote = "1.0.21"

### esp ###
wasmi = "0.20.0"

### server ###
axum = "0.6.19"
hyper = { version = "0.14.27", features = ["full"] }
axum-server = { version = "0.5.1", features = ["tls-rustls"] }
tower = "0.4.13"
tower-http = { version = "0.4.3", features = ["fs", "cors"] }
tower-livereload = "0.8.0"

### browser ###
fantoccini = "0.19.3"

### wasm ###
js-sys = "0.3.63"
wasm-bindgen = "0.2.86"
wasm-bindgen-futures = "0.4.36"
console_error_panic_hook = "0.1.7"
leptos = "0.3.1"
leptos_router = { version = "0.3.1", features = ["csr"] }
cssparser = "0.31.2"

#https://rustwasm.github.io/wasm-bindgen/api/web_sys/
#https://github.com/rustwasm/wasm-bindgen/blob/main/crates/web-sys/Cargo.toml
[workspace.dependencies.web-sys]
version = "0.3.61"
features = [
	# HTML
	'Headers',
	'Document',
	'Element',
	'Window',
	'ResizeObserver',
	'ResizeObserverBoxOptions',
	'ResizeObserverEntry',
	'ResizeObserverOptions',
	'ResizeObserverSize',
	'DomRectReadOnly',
	# Events
	'MouseEvent',
	'KeyboardEvent',
	# JS
	'Gpu',
	'console',
	'Navigator',
	'Performance',
	'WebGl2RenderingContext',
	# Audio
	'AudioContext',
	'AudioDestinationNode',
	'AudioNode',
	'AudioParam',
	'BiquadFilterNode',
	'BiquadFilterOptions',
	'BiquadFilterType',
	'DelayNode',
	'DelayOptions',
	'GainNode',
	'OscillatorNode',
	'OscillatorType',
	# Fetch
	'Request',
	'RequestInit',
	'RequestMode',
	'Response',
	# Blob
	'Blob',
	'BlobEvent',
	'BlobEventInit',
	'BlobPropertyBag',
	# Elements
	'HtmlAnchorElement',
	'HtmlCanvasElement',
	'HtmlInputElement',
	'File',
	'FileList',
	# Url
	'Url',
	'History',
	'Location',
	'UrlSearchParams',
	# Sensors
	'DeviceOrientationEvent',
	'DeviceMotionEvent',
	'DeviceAcceleration',
	'DeviceRotationRate',
	# Sockets
	'BinaryType',
	'FileReader',
	'ErrorEvent',
	'MessageEvent',
	'ProgressEvent',
	'WebSocket',
	# XR
	'XrBoundedReferenceSpace',
	'XrEye',
	'XrFrame',
	'XrHandedness',
	'XrInputSource',
	'XrInputSourceArray',
	'XrInputSourceEvent',
	'XrInputSourceEventInit',
	'XrInputSourcesChangeEvent',
	'XrJointPose',
	'XrJointSpace',
	'XrPose',
	'XrReferenceSpace',
	'XrReferenceSpaceEvent',
	'XrReferenceSpaceEventInit',
	'XrReferenceSpaceType',
	'XrRenderState',
	'XrRenderStateInit',
	'XrRigidTransform',
	'XrSession',
	'XrSessionEvent',
	'XrSessionEventInit',
	'XrSessionInit',
	'XrSessionMode',
	'XrSpace',
	'XrTargetRayMode',
	'XrView',
	'XrViewerPose',
	'XrViewport',
	'XrVisibilityState',
	'XrWebGlLayer',
	'XrWebGlLayerInit',
	'XrSystem',
]
