# https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
# wgpu needs this
resolver = "2"
members = [
	# "crates/*"
	"crates/forky",
	"crates/forky_core",
	"crates/forky_cli",
	# "crates/forky_esp",
	"crates/forky_play",
	"crates/forky_test",
	"crates/sweet",
]
[workspace.package]
version = "0.1.9"
edition = "2021"
license-file = "LICENSE"
readme = "README.md"
authors = ["Peter Hayman <peteyhayman@gmail.com>"]
description = "Rust Utilities"
documentation = "https://github.com/mrchantey/forky"
repository = "https://github.com/mrchantey/forky"

[workspace.dependencies]
# internal
forky = {path = "./crates/forky", version = "0.1.9" }
forky_core = {path = "./crates/forky_core", version = "0.1.9" }
forky_cli = {path = "./crates/forky_cli", version = "0.1.9" }
forky_esp = {path = "./crates/forky_esp", version = "0.1.8" }
forky_play = {path = "./crates/forky_play", version = "0.1.9" }
forky_test = {path = "./crates/forky_test", version = "0.1.9" }
sweet = {path = "./crates/sweet", version = "0.*" }

# game
bevy = { version = "0.8.1" }
# bevy = { version = "0.8.1", features = ["dynamic"] }
bevy-inspector-egui = "0.13.0"
bevy_rapier3d = {version = "0.18.0", features=["debug-render"]}
rand = "0.8.5"
inventory = "0.3.2"

# utility
notify = "5.0.0-pre.15"
crossterm = "0.25.0"
colorize = "0.1.0"
gag = "1.0.0"

# compile
backtrace = "0.3.66"
proc-macro2 = "1.0.47"
syn = {version="1.0.103",features= ["full"] }
quote = "1.0.21"

extend = "1.1.2"
