[package]
name = "forky_core"
version = {workspace=true}
edition = {workspace=true}
license-file = {workspace=true}
readme = {workspace=true}
description = {workspace=true}
repository = {workspace=true}


[dependencies]
crossterm = {workspace = true}

[dev-dependencies]
forky_test = {path="../forky_test"}
inventory = {workspace = true}

[[test]]
name = "forky"
path = "test/main.rs"
harness = false
