[package]
name = "forky_core"
version = "0.1.0"
edition = "2021"


[dependencies]
crossterm = {workspace = true}

[dev-dependencies]
forky_test = {path="../forky_test"}
inventory = {workspace = true}

[[test]]
name = "forky"
path = "tests/main.rs"
harness = false
