[package]
name = "gamai_macros"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
documentation = { workspace = true }
license = { workspace = true }
readme = "README.md"
description = "macro crate for gamai"
repository = { workspace = true }


[lib]
proc-macro = true

[dependencies]
anyhow = { workspace = true }
syn = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
