[package]
name = "sweet"
version = {workspace=true}
edition = {workspace=true}
license-file = {workspace=true}
# readme = "README.md"
description = {workspace=true}
repository = {workspace=true}

[dependencies]
forky_core = {workspace = true}
inventory = {workspace = true}
crossterm = {workspace = true}
colorize = "0.1.0"
gag = "1.0.0"
backtrace = "0.3.66"
proc-macro2 = "1.0.47"
syn = {version="1.0.103",features= ["full"] }
quote = "1.0.21"

[dev-dependencies]
forky_test = {workspace = true }
inventory = {workspace = true}

[[test]]
name = "forky"
path = "test/main.rs"
harness = false


[lib]
proc-macro = true
# path = "src/_lib.rs"