[package]
name = "sweet"
description = "Declarative testing framework"
categories = ["development-tools::testing"]
readme = "README.md"
version = {workspace=true}
edition = {workspace=true}
authors = {workspace=true}
documentation = {workspace=true}
license-file = {workspace=true}
repository = {workspace=true}

[dependencies]
forky_core = {workspace = true}
forky_test = {workspace = true}
inventory = {workspace = true}
crossterm = {workspace = true}
colorize = {workspace = true}
gag = {workspace = true}
backtrace = {workspace = true}

[[test]]
name = "sweet"
path = "test/sweet.rs"
harness = false
