[package]
name = "forky_wasm"
version = {workspace=true}
edition = {workspace=true}
authors = {workspace=true}
documentation = {workspace=true}
license-file = {workspace=true}
readme = {workspace=true}
description = {workspace=true}
repository = {workspace=true}

[dependencies]
rgb = "0.8.34"
wasmi = {workspace = true}
extend = {workspace=true}

[dev-dependencies]
forky_core = {workspace = true}
sweet = {workspace = true}

# [build-dependencies]

[[test]]
name = "sweet"
path = "test/sweet.rs"
harness = false
