[build]
# target = "x86_64-pc-windows-msvc"
rustflags = "-A incomplete_features"
## Uncomment below to ignore the pesky warnings during development
# rustflags = "-A dead_code -A unused_variables -A unused_imports -A unused_parens"

# Bevy optimizations ##
# will probably break cicd
# [target.x86_64-pc-windows-msvc]
# linker = "rust-lld.exe"
# rustflags = ["-Zshare-generics=n"]

### WASM ###

# [target.x86_64-pc-windows-msvc]
# rustflags = [
#  "--cfg","web_sys_unstable_apis"
# ]

# [target.wasm32-unknown-unknown]
# runner = "wasm-server-runner"
# rustflags = [
#  "--cfg","web_sys_unstable_apis",
# ]
### ESP32 ###

[target.riscv32imc-unknown-none-elf]
runner = "espflash --monitor"
rustflags = ["-C", "link-arg=-Tlinkall.x"]

# for testing: you can specify this target to see atomic emulation in action
[target.riscv32imac-unknown-none-elf]
runner = "espflash --monitor"
rustflags = ["-C", "link-arg=-Tlinkall.x"]
