name: Build and Deploy Book

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust environment
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Install mdbook
        run: cargo install mdbook

      - name: Build book
        run: mdbook build ./book

      - name: Copy book to pages branch
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout -b pages
          rm -rf ./book || true
          cp -r ./book ./book
          git add .
          git commit -m "Update book"
          git push -f origin pages