name: Test Repo
on:
  push:
    branches: main
    paths: ['**','!**/*.md']
  pull_request:
    branches: main
    paths: ['**','!**/*.md']
env:
  CARGO_TERM_COLOR: always
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: 📂 Checkout
      uses: actions/checkout@v3
    - name: 📂 Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-v1
    - name: 🔨 Install Just
      uses: extractions/setup-just@v1
    - name: 🔨 Install Chromedriver
      uses: nanasess/setup-chromedriver@v2
    - name: 🔨 Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        default: true
        components: rustfmt, clippy
    - name: 🔨 Install Wasm Target
      run: rustup target add wasm32-unknown-unknown
    - name: 🔨 Install Wasm Bindgen
      run: cargo install -f wasm-bindgen-cli
    - name: 🔎 Test Native
      run: just test-all
    - name: 🔎 Test Wasm
      run: just test-all-wasm