name: Test Repo

on:
  push:
    branches:
      - main
    # paths:
    #   - '**/*.rs'
  pull_request:
    branches:
      - main
    # paths:
    #   - '**/*.rs'
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: extractions/setup-just@v1
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        default: true
        components: rustfmt, clippy
        # target: wasm32-unknown-unknown
    - name: Check
      run: just --version
    - name: Cargo
      run: cargo --version
    - name: Test
      run: just test forky_core