name: Test Repo

on:
  push:
    branches:
      - main
    # paths:
    #   - '**/*.rs'
  pull_request:
    branches:
      - main
    # paths:
    #   - '**/*.rs'
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: extractions/setup-just@v1
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        default: true
        components: rustfmt, clippy
    - name: Test Native
      run: just test-all
    - name: Install Wasm Target
      run: rustup target add wasm32-unknown-unknown
    - name: Install Wasm Bindgen
      run: cargo install -f wasm-bindgen-cli
    - name: Install ChromeDriver
      uses: nanasess/setup-chromedriver@v2

    - name: Test Wasm
      run: just test-all-wasm